#!/bin/bash

python tagRecall1102.py text_nb/nb_allcorpus140w_all_user_big5_dict all.corpus.140w.seg.all.user.dict.df.big5.dict root_feature_file.all root_type_file concept_tag.txt category_ability_info adv_nb_lr/nb.big40.14w adv_nb_lr/lr.big40.14w adv.train.seg.tf.big40.dict online_class.list qiyi.online catagery.induce.type.ok catagery.induce.id.ok catagery.induce.word.ok uid.list lev1.id2name all.features.user.dict.end uid_ability_score 30 3600 ../data/indir  ../data/tmpdir  ../data/outdir  ../data/bakdir 256 0 8 0 0 uid.c13 category_ability_info root_feature_file.allid deep_online_list adv_gbdt/model_gbrlr_merge_zzy adv_gbdt/model_gbr_merge_zzy adv_gbdt/model_onehotEncoder_zzy

#python tagRecall1008.py text_nb/nb_allcorpus140w_all_user_big5_dict all.corpus.140w.seg.all.user.dict.df.big5.dict root_feature_file.all root_type_file concept_tag.txt category_ability_info adv_nb_lr/nb.big40.14w adv_nb_lr/lr.big40.14w adv.train.seg.tf.big40.dict online_class.list qiyi.online catagery.induce.type.ok catagery.induce.id.ok catagery.induce.word.ok uid.list lev1.id2name all.features.user.dict.end uid_ability_score 30 3600 ../data/indir  ../data/tmpdir  ../data/outdir  ../data/bakdir 256 0 8 0 0 uid.c13 category_ability_info root_feature_file.allid deep_online_list adv_gbdt/model_gbrlr_merge_zzy adv_gbdt/model_gbr_merge_zzy adv_gbdt/model_onehotEncoder_zzy

#python tagRecall1031.py text_nb/nb_allcorpus140w_all_user_big5_dict all.corpus.140w.seg.all.user.dict.df.big5.dict root_feature_file.all root_type_file concept_tag.txt category_ability_info adv_nb_lr/nb.big40.14w adv_nb_lr/lr.big40.14w adv.train.seg.tf.big40.dict online_class.list qiyi.online catagery.induce.type.ok catagery.induce.id.ok catagery.induce.word.ok uid.list lev1.id2name all.features.user.dict.end uid_ability_score 30 3600 ../data/indir  ../data/tmpdir  ../data/outdir  ../data/bakdir 256 0 8 0 0 uid.c13 category_ability_info root_feature_file.allid deep_online_list adv_gbdt/model_gbrlr_merge_zzy adv_gbdt/model_gbr_merge_zzy adv_gbdt/model_onehotEncoder_zzy

#python tagRecall0329.py text_nb/nb_allcorpus140w_all_user_big5_dict all.corpus.140w.seg.all.user.dict.df.big5.dict root_feature_file.all root_type_file concept_tag.txt category_ability_info adv_nb_lr/nb.big40.14w adv_nb_lr/lr.big40.14w adv.train.seg.tf.big40.dict online_class.list qiyi.online catagery.induce.type.ok catagery.induce.id.ok catagery.induce.word.ok uid.list lev1.id2name all.features.user.dict.end uid_ability_score 30 3600 ../data/indir  ../data/tmpdir  ../data/outdir  ../data/bakdir 256 0 4 0 0 uid.c13 category_ability_info root_feature_file.allid
